# This file contains all labels to synchronize across all my repositories
# The synchronization process is handled by the GitHub action `sync-label`
- name: dependencies
  description: Issue or pull request that involves a dependency
  color: 0366d6
