name: "Bug report"
description: "Report a problem you're experiencing with the repository"
labels: 
  - bug

body:
  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the bug"
      description: "Describe what the bug is as well as how it affects what you are trying to achieve."
      
  - id: what-you-see
    type: textarea
    attributes:
      label: "What do you see?"
      description: "Describe the (flawed) behavior you currently see"
      
  - id: what-you-expect
    type: textarea
    attributes:
      label: "What do you expect to see?"
      description: "Describe the correct behavior you expect to see"

  - id: steps-to-reproduce
    type: textarea
    validations:
      required: false
    attributes:
      label: "List the steps that must be taken to reproduce this issue"
      description: "Provide a list of steps needed to reproduce the behavior. If any code or configuration is involved, please make sure to format it."
      placeholder: |
        1. Start the application
        2. Navigate to localhost:8080/metrics
        3. No metrics are displayed

  - id: version
    type: input
    attributes:
      label: "Version"
      description: "What version are you using?"
      
  - id: additional-information
    type: textarea
    attributes:
      label: "Additional information"
      description: "Add any other information about the bug here"
