name: "Bug report"
description: "Report a problem you're experiencing with the repository"
labels: 
  - bug

body:
  - id: bug-description
    type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the bug"
      description: "Describe what the bug is as well as how it affects what you are trying to achieve."
      
  - id: what-you-see
    type: textarea
    attributes:
      label: "What do you see?"
      description: "Describe the (flawed) behavior you currently see"
      
  - id: what-you-expect
    type: textarea
    attributes:
      label: "What do you expect to see?"
      description: "Describe the correct behavior you expect to see if this bug was resolved"

  - id: steps-to-reproduce
    type: textarea
    validations:
      required: true
    attributes:
      label: "List the steps that must be taken to reproduce this issue"
      description: "Provide a list of steps needed to reproduce the behavior. If any code or configuration is involved, please make sure to format it."

