name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-list-of-repositories
        id: repositories
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - run: echo ${{steps.repositories.outputs.repoList}}
      - uses: micnncim/action-label-syncer@v1
        with:
          token: ${{ secrets.TOKEN_WITH_RW_ACCESS_TO_ISSUES }}
          prune: false
          manifest: .github/labels.yml
          repository: |
            TwiN/.github
